name: Renovatebot

on: workflow_dispatch

permissions:
  pull-requests: write
  security-events: write

jobs:
  renovatebot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v41.0.18
      # with:
        # token: ${{ secrets.GITHUB_TOKEN }}
        # token: ${{ secrets.RENOVATE_TOKEN }}
        # configurationFile: renovate.json
      env:
        # LOG_LEVEL: debug
        # RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        # RENOVATE_DRY_RUN: true
