name: Renovatebot

on: workflow_dispatch

env:
  REPORT_DIR: renovatebot-reports

jobs:
  renovatebot:
    runs-on: ubuntu-latest
    steps:
    - name: Echo api url
      run: echo "${{ github.api_url }}"
    
    - name: Checkout
      uses: actions/checkout@v4.2.2

    # - name: Generate report folder
    #   run: |
    #     mkdir -p ${REPORT_DIR}

    - name: Determine current user
      id: id
      run: |
        echo "user=$(id -u)" >> $GITHUB_OUTPUT
        echo "group=$(id -g)" >> $GITHUB_OUTPUT

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v41.0.21
      with:
        docker-user: "${{ steps.id.outputs.user }}:${{ steps.id.outputs.group }}"
        docker-volumes: /tmp/report:/tmp/report
      env:
        LOG_LEVEL: debug
        RENOVATE_TOKEN: ${{ github.token }}
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        # RENOVATE_DRY_RUN: true
        RENOVATE_REPORT_TYPE: file
        RENOVATE_REPORT_PATH: /tmp/report/report.json
        HOME: ${{ github.workspace }}
    
    - name: Renovatebot report
      run: |
          echo "/tmp/report/report.json"
