name: Renovatebot

on: workflow_dispatch

jobs:
  renovatebot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v41.0.18
      env:
        LOG_LEVEL: debug
        RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        # RENOVATE_DRY_RUN: true
