name: Renovatebot

on: workflow_dispatch

jobs:
  renovatebot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v41.0.18
      with:
        token: ${{ secrets.RENOVATE_TOKEN }}
        repositories: ${{ github.repository }}
      env:
        # LOG_LEVEL: debug
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        # configurationFile: renovate.json
