name: Renovatebot

on: workflow_dispatch

env:
  REPORT_DIR: ${{ github.workspace }}/renovatebot-reports

jobs:
  renovatebot:
    runs-on: ubuntu-latest
    steps:
    - name: Echo api url
      run: echo "${{ github.api_url }}"
    
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Generate report folder
      run: |
        mkdir -p ${BUILD_DIR}

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v41.0.18
      env:
        LOG_LEVEL: debug
        RENOVATE_TOKEN: ${{ github.token }}
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        # RENOVATE_DRY_RUN: true
        RENOVATE_REPORT_TYPE: file
        RENOVATE_REPORT_PATH: ${BUILD_DIR}/renovatebot-report.json
        HOME: ${{ github.workspace }}
    
    - name: Renovatebot report
      run: |
          echo "${BUILD_DIR}/renovatebot-report.json"
