name: Renovatebot

on: workflow_dispatch

jobs:
  conan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v41.0.18
      with:
        token: ${{ secrets.RENOVATE_TOKEN }}
